[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "turingpy"
version = "0.0.1"
authors = [ {name = "Haralampos Protoolis"} ]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"

[project.optional-dependencies]
cli = ["rich"]